// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function($) {
  var JQueryAce, _ref;
  JQueryAce = (function() {
    function JQueryAce() {}

    JQueryAce.prototype.initialize = function(element, options) {
      var klass;
      klass = (function() {
        switch (true) {
          case $(element).is('textarea'):
            return JQueryAce.TextareaEditor;
          default:
            return JQueryAce.BaseEditor;
        }
      })();
      return new klass(element, options);
    };

    JQueryAce.prototype.defaults = {
      theme: null,
      lang: null,
      mode: null,
      width: null,
      height: null
    };

    JQueryAce.prototype.version = '1.0.3';

    JQueryAce.prototype.require = function() {
      switch (true) {
        case typeof ace.require === 'function':
          return ace.require.apply(null, arguments);
        case typeof window.require === 'function':
          return window.require.apply(null, arguments);
        default:
          throw "Can't find 'require' function";
      }
    };

    return JQueryAce;

  })();
  JQueryAce.BaseEditor = (function() {
    function BaseEditor(element, options) {
      if (options == null) {
        options = {};
      }
      this.element = $(element);
      this.options = $.extend({}, JQueryAce.defaults, options);
    }

    BaseEditor.prototype.create = function() {
      this.editor = new JQueryAce.AceDecorator(ace.edit(this.element));
      return this.update();
    };

    BaseEditor.prototype.update = function(options) {
      var lang;
      if (options != null) {
        this.options = $.extend({}, this.options, options);
      }
      if (this.options.theme != null) {
        this.editor.theme(this.options.theme);
      }
      lang = this.options.lang || this.options.mode;
      if (lang != null) {
        return this.editor.lang(lang);
      }
    };

    BaseEditor.prototype.destroy = function() {
      this.element.data('ace', null);
      this.editor.destroy();
      return this.element.empty();
    };

    return BaseEditor;

  })();
  JQueryAce.TextareaEditor = (function(_super) {
    __extends(TextareaEditor, _super);

    function TextareaEditor() {
      _ref = TextareaEditor.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TextareaEditor.prototype.show = function() {
      var _ref1;
      if ((_ref1 = this.container) != null) {
        _ref1.show();
      }
      return this.element.hide();
    };

    TextareaEditor.prototype.hide = function() {
      var _ref1;
      if ((_ref1 = this.container) != null) {
        _ref1.hide();
      }
      return this.element.show();
    };

    TextareaEditor.prototype.create = function() {
      var _this = this;
      this.container = this.createAceContainer();
      this.editor = new JQueryAce.AceDecorator(ace.edit(this.container.get(0)));
      this.update();
      this.editor.value(this.element.val());
      this.editor.ace.on('change', function(e) {
        return _this.element.val(_this.editor.value());
      });
      return this.show();
    };

    TextareaEditor.prototype.destroy = function() {
      TextareaEditor.__super__.destroy.call(this);
      this.hide();
      return this.container.remove();
    };

    TextareaEditor.prototype.createAceContainer = function() {
      return this.buildAceContainer().insertAfter(this.element);
    };

    TextareaEditor.prototype.buildAceContainer = function() {
      return $('<div></div>').css({
        display: 'none',
        position: 'relative',
        width: this.options.width || this.element.width(),
        height: this.options.height || this.element.height()
      });
    };

    return TextareaEditor;

  })(JQueryAce.BaseEditor);
  JQueryAce.AceDecorator = (function() {
    function AceDecorator(ace) {
      this.ace = ace;
    }

    AceDecorator.prototype.theme = function(themeName) {
      return this.ace.setTheme("ace/theme/" + themeName);
    };

    AceDecorator.prototype.lang = function(modeName) {
      var klass;
      klass = JQueryAce.require("ace/mode/" + modeName).Mode;
      return this.session().setMode(new klass);
    };

    AceDecorator.prototype.mode = function(modeName) {
      return this.lang(modeName);
    };

    AceDecorator.prototype.session = function() {
      return this.ace.getSession();
    };

    AceDecorator.prototype.destroy = function() {
      return this.ace.destroy();
    };

    AceDecorator.prototype.value = function(text) {
      if (text != null) {
        return this.ace.insert(text);
      } else {
        return this.ace.getValue();
      }
    };

    return AceDecorator;

  })();
  $.ace = function(element, options) {
    return $(element).ace(options);
  };
  return $.fn.ace = function(options) {
    var jqs;
    jqs = new JQueryAce();
    return this.each(function() {
      var editor;
      editor = $(this).data('ace');
      if (editor != null) {
        return editor.update(options);
      } else {
        editor = jqs.initialize(this, options);
        editor.create();
        return $(this).data('ace', editor);
      }
    });
  };
})(jQuery);
